### ISSUE TITLE
插件导致HAOS频繁奔溃卡死

### ISSUE THREAD

**Issue by chaosl1996** [knoop7/ha_laohuangli#3]
![image](https://github.com/user-attachments/assets/c50b2b2a-25d0-425f-9af3-dca793bf6596)
如图所示supervisor每隔70分钟左右会报错崩溃，导致系统重启卡死。
已经使用2个不同设备测试，都是os版本，禁用集成就好。

系统版本信息：
硬件信息：                Generic x86-64
Core:                          2024.11.2
Supervisor:                 2024.11.3
Operating System:     13.2
Frontend:                    20241106.2

官网论坛也有很多[相同问题](https://community.home-assistant.io/t/home-assistant-wont-connect-after-2024-10/777881/3)，大家后面发现是Alexa的问题。

**Comment by knoop7** [comment]
新版已解决逻辑问题，不过和集成没关系，前段时间10.4我也异常崩溃过，也是容器不过在我的测试机当中

**Comment by knoop7** [comment]
更新最新版本

**Comment by chaosl1996** [comment]
似乎还是老样子，经过实际测试发现：

具体表现为直接添加集成后等待一天正常使用，

但是当添加生日管理后就会再次出现循环卡死的问题。

**Comment by knoop7** [comment]
> 似乎还是老样子，经过实际测试发现：
> 
> 具体表现为直接添加集成后等待一天正常使用，
> 
> 但是当添加生日管理后就会再次出现循环卡死的问题。

老黄历传感器，是没问题这部分基本上没问题，关键点确实生日管理这里我在修复，是因为修复老黄历导致的生日传感器损坏，我在尝试解决这个问题

**Comment by chaosl1996** [comment]
好的，我试试
感谢大佬
